name: Container
on:
  push:
    paths:
      - '.github/workflows/container.yml'
  workflow_dispatch:

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:  # any step that we define will run inside this docker
      image: node:16.16.0-alpine3.15
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
