name: Matrix
on:
  push:
    paths:
      - '.github/workflows/matrix.yml'
  workflow_dispatch:

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
      exclude: # it will not run this combination
        - os: ubuntu-latest
          node-version: 6
        - os: macos-latest
          node-version: 6
      include: #includes extra variables for certain configuration that already exist in matrix
        - os: ubuntu-latest
          node-version: 6
          is_ubuntu_8: 'true'        
      max-parallel: 2

      fail-fast: true # if one of jobs fail, all other jobs will stop
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8}}
    steps:
      - name: Log Node Version
        run: node -v

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Log Node Version
        run: node -v

      - name: Additional variable from matrix include
        run: echo $IS_UBUNTU_8
